### ISSUE TITLE
Having issues with create-service it does not create default credentials

### ISSUE THREAD

**Issue by adamgins** [IBM-Cloud/compose-mongodb-helloworld-nodejs#3]
Hi, when I run `cf create-service compose-for-mongodb Standard some-service-id` it creates the services but the creds are blank. 

![screen shot 2017-03-09 at 2 36 20 pm](https://cloud.githubusercontent.com/assets/7233741/23736563/37520890-04e1-11e7-9960-2a064beb44e1.png)

BTW, I was actually trying to do this in a Devops pipeline but I het the same issue when I just create the service from the command line:

```
#!/bin/bash
cf create-service compose-for-mongodb Standard "mongodb-${CF_APP}"
cf push "${CF_APP}" --no-start
cf bind-service "${CF_APP}" "mongodb-${CF_APP}"
cf restage "${CF_APP}"
```
BTW, I had dumbed down my manifest to:

```
applications:
  - name: appname 
    domain: au-syd.mybluemix.net
    host: hostName
```

Any ideas pls?
